#!/usr/bin/env node
'use strict';

var express = require('express');
var app = express(),
    bodyParser = require('body-parser'),
    program = require('commander');

program
    .option('-p, --port <int>', 'Port number', 3030);


app.use(bodyParser.urlencoded({ extended: false }));
app.use(bodyParser.json());

app.put('/api/:clientid/groups/0/action', function (req, res) {
    console.log('req', req.originalUrl, req.body, req.params);
    res.send([{'success': true}]);
});


var server = app.listen(program.port, function () {
    var host = server.address().address,
        port = server.address().port;

    console.log('Hue mock server listening at http://%s:%s', host, port);
});
