#!/usr/bin/env python
# -*- coding: utf-8 -*-

import signal, sys

def quit_gracefully(*args):
    print 'quitting loop'
    sys.exit(0);

if __name__ == "__main__":
    signal.signal(signal.SIGINT, quit_gracefully)

    try:
        print 'starting loop'
        while True:
            pass
    except KeyboardInterrupt:
        quit_gracefully()
